In [7]:
import pandas as pd 

test_true = pd.read_csv("data/Test_data/real_missions/data-10.csv", sep=',', low_memory=False)
test_false = pd.read_csv("data/Test_data/fake_missions/data-10.csv", sep=',', low_memory=False)
test_true

,timestamp,pitch,yaw,roll,lat,lon,alt,velocity_x,velocity_y,velocity_z,battery,heading,airspeed,groundspeed
0,0,0.007639,0.010040,-0.027700,36.715607,3.184630,18.89,-0.01,0.02,0.04,96,0,0.053715,0.031270
1,1,-0.052302,0.007827,0.122185,36.715608,3.184632,18.88,0.29,0.51,0.00,95,0,0.599283,0.599281
2,2,-0.217288,1.492763,-0.075624,36.715622,3.184661,18.84,1.62,2.59,-0.02,95,85,3.065288,3.065143
3,3,-0.169591,0.919952,-0.023820,36.715649,3.184714,18.89,2.18,3.48,-0.03,95,52,4.115614,4.115439
4,4,0.008612,0.973084,0.025449,36.715679,3.184771,18.92,1.99,3.08,-0.02,94,55,3.673969,3.673905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,60,-0.262258,-2.099530,0.026376,36.714029,3.180879,18.95,-3.23,-5.64,0.00,72,239,6.503362,6.503358
61,61,-0.221996,-2.100204,-0.016592,36.713985,3.180784,18.95,-3.12,-5.46,0.00,71,239,6.293349,6.293348
62,62,0.142790,-2.101222,-0.020024,36.713944,3.180695,18.93,-1.80,-3.13,0.03,71,239,3.620962,3.620762
63,63,0.098638,-2.100843,0.015608,36.713931,3.180666,18.93,-0.31,-0.56,-0.02,71,239,0.645336,0.644846
64,64,-0.016204,-2.101371,0.020066,36.713931,3.180665,18.92,0.16,0.11,0.04,70,239,0.205206,0.200788

In [8]:
test_false

,timestamp,pitch,yaw,roll,lat,lon,alt,velocity_x,velocity_y,velocity_z,battery,heading,airspeed,groundspeed
0,0,-0.016789,-0.013516,0.019092,36.715607,3.184630,15.61,-0.03,0.03,-0.05,96,359,0.069545,0.045658
1,1,-0.069874,-0.005095,0.063138,36.715608,3.184632,15.64,0.44,0.52,-0.02,95,359,0.692141,0.691698
2,2,-0.253168,1.148573,-0.066674,36.715625,3.184653,15.65,2.16,2.19,-0.07,95,65,3.086693,3.085820
3,3,-0.234158,0.828631,0.005402,36.715670,3.184712,15.63,3.36,3.40,0.02,95,47,4.786785,4.786725
4,4,-0.081001,0.789302,-0.007667,36.715717,3.184769,15.64,3.28,3.30,-0.01,94,45,4.662523,4.662484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,60,-0.272554,-2.103653,0.038728,36.714106,3.180927,15.67,-3.25,-5.64,0.00,72,239,6.513872,6.513867
61,61,-0.271725,-2.099653,-0.027337,36.714062,3.180832,15.66,-3.22,-5.67,0.01,72,239,6.527733,6.527725
62,62,0.029569,-2.100412,0.010699,36.714016,3.180730,15.66,-2.40,-4.19,0.02,71,239,4.835837,4.835760
63,63,0.127314,-2.101069,-0.013224,36.713994,3.180683,15.64,-0.75,-1.33,-0.01,71,239,1.532264,1.532220
64,64,0.024463,-2.100601,-0.021496,36.713991,3.180676,15.65,0.11,0.16,0.00,70,239,0.197434,0.197190

# **Prediction LSTM**

In [3]:
import pandas as pd
import numpy as np
import time
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler

test_model = load_model("Models\Lstm_Many_to_one_1.h5")
# test_model = model

def prediction(mission, point=64):

    scaler = StandardScaler()
    mission_std = scaler.fit_transform(mission)
    mission_std = pd.DataFrame(mission_std, columns=mission.columns)

    # data = mission
    data = mission_std
    # data = mission

    sequence_length = 4
    sequences = []
    for i in range(0, len(data) - sequence_length + 1):
        sequence = data.iloc[i:i + sequence_length].values
        sequences.append(sequence)

    X = np.array(sequences)

    print(X.shape)
    
    sart_time = time.time()
    result = test_model.predict(X)
    end_time = time.time()
    print("Prediction result: ", (result[0:point] > 0.5).astype(int))
    # print("Prediction result: ", result)
    print("prediction time : ",end_time-sart_time)

In [6]:
mission = test_true[:]
# mission = test_false[:]


prediction(mission, 30)

(62, 4, 14)
2/2 [==============================] - 0s 3ms/step
Prediction result:  [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
prediction time :  0.07183647155761719

# **Prediction MLP**

In [9]:
import pandas as pd
import numpy as np
import time
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler

model = load_model("Models\mlp2.h5")

def prediction(mission):

    # scaler = StandardScaler()
    # mission_std = scaler.fit_transform(mission)
    # mission_std = pd.DataFrame(mission_std, columns=mission.columns)

    # data = mission_std
    data = mission
    # print(data.shape)
    
    sart_time = time.time()
    result = model.predict(data)
    end_time = time.time()
    print("Prediction result: ", (result > 0.5).astype(int))
    # print("Prediction result: ", result)
    print("prediction time : ",end_time-sart_time)

In [11]:
test_true = pd.read_csv("data/Test_data/real_missions/data-10.csv", sep=',', low_memory=False)
mission = test_true

# test_false = pd.read_csv("data/Test_data/fake_missions/data-1.csv", sep=',', low_memory=False)
# mission = test_false
prediction(mission)

1/1 [==============================] - 0s 17ms/step
Prediction result:  [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
prediction time :  0.059375762939453125